# Mark Shust's Docker Configuration for Magento (https://github.com/markshust/docker-magento)
# Version 25.0.0

version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.13-7
    ports:
      - "80:8000"
      - "443:8443"
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:delegated
      - ./src/:/var/www/html:delegated
      - sockdata:/sock

  phpfpm:
    image: markoshust/magento-php:7.2-fpm-2
    links:
      - db
    volumes: *appvolumes

  db:
    image: percona:5.6
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - ~/.docker/db/data:/var/lib/mysql:delegated

  redis:
    image: redis:5.0

  elasticsearch:
    image: markoshust/magento-elasticsearch:6.5.4-0
    ports:
      - "9200:9200"
      - "9300:9300"

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  image: markoshust/magento-php:7.3-fpm-1
  #  user: root
  #  command: /usr/local/bin/cronstart
  #  tty: true
  #  links:
  #    - db
  #  volumes: *appvolumes

volumes:
  sockdata:
